name: Deploying to prod
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything 

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 13.232.75.188 >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@13.232.75.188 "cd portfolio && git pull && npm install && npm run build && cd server && npm install && pm2 restart portfolio"

